version: '3.8'
services:
  client-backend:
    image: client:0.0.1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8881:8881"
    depends_on:
      - service-db
    environment:
      - SERVER_PORT= 8881
      - SPRING_DATASOURCE_URL=jdbc:postgresql://service-db/warehouse

  service-db:
    image: postgres:14.7-alpine
    environment:
      POSTGRES_USER: warehouse_admin
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - ./src/main/resources/liquibase/scripts/create_db.sql:/docker-entrypoint-initdb.d/create_db.sql
      - db-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  db-data: